name: Motoqueros
rules:
  - { image: fondo.png,         when: { black: 0, blue: 0, green: 0, red: 0 } }
  - { image: motoquero1.png,    when: { black: 1, blue: 0, green: 0, red: 0 } }
  - { image: motoquero2.png,    when: { black: 2, blue: 0, green: 0, red: 0 } }
  - { image: motoquero3.png,    when: { black: 3, blue: 0, green: 0, red: 0 } }
  - { image: motoquero4.png,    when: { black: 4, blue: 0, green: 0, red: 0 } }
  - { image: motoquero5.png,    when: { black: 5, blue: 0, green: 0, red: 0 } }
  - { image: motoquero1-01.png, when: { black: 1, blue: 0, green: 0, red: 1 } }
  - { image: motoquero2-01.png, when: { black: 2, blue: 0, green: 0, red: 1 } }
  - { image: motoquero3-01.png, when: { black: 3, blue: 0, green: 0, red: 1 } }
  - { image: motoquero4-01.png, when: { black: 4, blue: 0, green: 0, red: 1 } }
  - { image: motoquero5-01.png, when: { black: 5, blue: 0, green: 0, red: 1 } }
  - { image: motoquero1-02.png, when: { black: 1, blue: 0, green: 0, red: 2 } }
  - { image: motoquero2-02.png, when: { black: 2, blue: 0, green: 0, red: 2 } }
  - { image: motoquero3-02.png, when: { black: 3, blue: 0, green: 0, red: 2 } }
  - { image: motoquero4-02.png, when: { black: 4, blue: 0, green: 0, red: 2 } }
  - { image: motoquero5-02.png, when: { black: 5, blue: 0, green: 0, red: 2 } }
  - { image: motoquero1-03.png, when: { black: 1, blue: 0, green: 0, red: 3 } }
  - { image: motoquero2-03.png, when: { black: 2, blue: 0, green: 0, red: 3 } }
  - { image: motoquero3-03.png, when: { black: 3, blue: 0, green: 0, red: 3 } }
  - { image: motoquero4-03.png, when: { black: 4, blue: 0, green: 0, red: 3 } }
  - { image: motoquero5-03.png, when: { black: 5, blue: 0, green: 0, red: 3 } }
  - { image: motoquero1-04.png, when: { black: 1, blue: 0, green: 0, red: 4 } }
  - { image: motoquero2-04.png, when: { black: 2, blue: 0, green: 0, red: 4 } }
  - { image: motoquero3-04.png, when: { black: 3, blue: 0, green: 0, red: 4 } }
  - { image: motoquero4-04.png, when: { black: 4, blue: 0, green: 0, red: 4 } }
  - { image: motoquero5-04.png, when: { black: 5, blue: 0, green: 0, red: 4 } }
  - { image: motoquero1-05.png, when: { black: 1, blue: 0, green: 0, red: 5 } }
  - { image: motoquero2-05.png, when: { black: 2, blue: 0, green: 0, red: 5 } }
  - { image: motoquero3-05.png, when: { black: 3, blue: 0, green: 0, red: 5 } }
  - { image: motoquero4-05.png, when: { black: 4, blue: 0, green: 0, red: 5 } }
  - { image: motoquero5-05.png, when: { black: 5, blue: 0, green: 0, red: 5 } }
  - { image: motoquero1-06.png, when: { black: 1, blue: 0, green: 0, red: 6 } }
  - { image: motoquero2-06.png, when: { black: 2, blue: 0, green: 0, red: 6 } }
  - { image: motoquero3-06.png, when: { black: 3, blue: 0, green: 0, red: 6 } }
  - { image: motoquero4-06.png, when: { black: 4, blue: 0, green: 0, red: 6 } }
  - { image: motoquero5-06.png, when: { black: 5, blue: 0, green: 0, red: 6 } }
  - { image: motoquero1-07.png, when: { black: 1, blue: 0, green: 0, red: 7 } }
  - { image: motoquero2-07.png, when: { black: 2, blue: 0, green: 0, red: 7 } }
  - { image: motoquero3-07.png, when: { black: 3, blue: 0, green: 0, red: 7 } }
  - { image: motoquero4-07.png, when: { black: 4, blue: 0, green: 0, red: 7 } }
  - { image: motoquero5-07.png, when: { black: 5, blue: 0, green: 0, red: 7 } }
  - { image: motoquero1-08.png, when: { black: 1, blue: 0, green: 0, red: 8 } }
  - { image: motoquero2-08.png, when: { black: 2, blue: 0, green: 0, red: 8 } }
  - { image: motoquero3-08.png, when: { black: 3, blue: 0, green: 0, red: 8 } }
  - { image: motoquero4-08.png, when: { black: 4, blue: 0, green: 0, red: 8 } }
  - { image: motoquero5-08.png, when: { black: 5, blue: 0, green: 0, red: 8 } }
  - { image: motoquero1-09.png, when: { black: 1, blue: 0, green: 0, red: 9 } }
  - { image: motoquero2-09.png, when: { black: 2, blue: 0, green: 0, red: 9 } }
  - { image: motoquero3-09.png, when: { black: 3, blue: 0, green: 0, red: 9 } }
  - { image: motoquero4-09.png, when: { black: 4, blue: 0, green: 0, red: 9 } }
  - { image: motoquero5-09.png, when: { black: 5, blue: 0, green: 0, red: 9 } }
