name: Paredes
rules:
  - { image: Fondo.png            , when: { black: 0, blue: 0, green: 0, red: 0 } }
  - { image: Cemento-1.png        , when: { black: 0, blue: 0, green: 0, red: 1 } }
  - { image: Ladrillo-1.png       , when: { black: 0, blue: 0, green: 1, red: 1 } }
  - { image: Cemento-2.png        , when: { black: 0, blue: 0, green: 1, red: 2 } }
  - { image: Ladrillo-2.png       , when: { black: 0, blue: 1, green: 1, red: 2 } }
  - { image: Ladrillo-completo.png, when: { black: 1, blue: 1, green: 1, red: 2 } }
